server {
    server_name 3.38.167.218;

    listen 80;

    resolver 127.0.0.11 valid=10s;
    set $fastapi_upstream http://fastapi:8000;

    # 추후 certbot ssl 인증서 갱신 시 필요
    location /.well-known/acme-challenge/ {
       root /var/www/certbot;
    }

    location /api/ {
        proxy_pass $fastapi_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_buffering off;
        proxy_read_timeout 300s;
        proxy_connect_timeout 300s;
    }

    location / {
        return 404;
    }
}
