window.APP_TEXTS = {
    common: {
        serviceName: 'HealthCare AI',
        serviceTagline: '당신의 곁에, 언제나',
        userFallbackName: '사용자',
    },
    sidebar: {
        sectionTitle: '나의 건강 서비스',
        menu: {
            dashboard: '대시보드',
            medications: '복약 관리',
            health: '일상 건강',
            scans: '처방전 스캔',
            recommendations: 'AI 맞춤 추천',
            chatbot: 'AI 건강 상담',
            profile: '내 프로필 설정',
            logout: '로그아웃',
        },
    },
    index: {
        title: '당신의 건강을 기원합니다 - 로그인',
        quotes: [
            '당신의 건강과 평안을 진심으로 기원합니다.',
            '오늘 하루도 무사히 이겨내기를 바랍니다.',
            '아픔은 덜고, 미소는 더하는 하루가 되길 응원합니다.',
            '힘든 시간을 잘 견뎌내는 당신이 자랑스럽습니다.',
            '작은 휴식이 모여 큰 치유가 될 것입니다.',
            '당신의 한 걸음 한 걸음을 늘 응원하겠습니다.',
            '오늘도 수고 많으셨습니다. 편안한 밤 되세요.',
            '치유는 시간의 흐름을 믿는 것에서 시작됩니다.',
            '스스로를 돌보는 것이 가장 위대한 용기입니다.',
            '당신은 혼자가 아닙니다. 우리가 곁에 있습니다.',
        ],
        startButton: '서비스 시작하기',
        loginTitle: '로그인',
        loginSubtitle: '서비스 이용을 위해 로그인해주세요.',
        signupTitle: '회원가입',
        signupSubtitle: '가입을 환영합니다.',
        reloginSubtitle: '다시 오신 것을 환영합니다.',
        fields: {
            email: '이메일',
            name: '이름',
            password: '비밀번호',
            passwordSetup: '비밀번호 설정',
            phone: '휴대폰 번호 (하이픈 - 포함)',
            gender: '성별',
            birthday: '생년월일 (YYYY-MM-DD)',
        },
        placeholders: {
            email: 'example@email.com',
            name: '홍길동',
            password: '••••••••',
            phone: '010-1234-5678',
        },
        buttons: {
            login: '로그인',
            signup: '회원가입 완료',
            goSignup: '회원가입',
            goLogin: '로그인하러 가기',
        },
        prompts: {
            noAccount: '계정이 없으신가요?',
            hasAccount: '이미 계정이 있으신가요?',
            genderSelect: '선택',
            genderMale: '남성',
            genderFemale: '여성',
            signupSuccess: '가입이 성공적으로 완료되었습니다. 보안을 위해 다시 로그인해주세요.',
        },
    },
    dashboard: {
        title: '건강 대시보드 요약',
        subtitle: '당신의 지난 건강 상태와 오늘의 할 일을 확인하세요.',
        loading: '정보를 불러오는 중입니다...',
        memberLabel: '정회원',
        phoneLabel: '연락처',
        birthLabel: '생년월일',
        profileButton: '상세 정보 기입하기',
        medicationSummaryTitle: '최근 복약 상태 요약',
        seeAll: '전체 보기',
        activeMeds: '현재 복용중인 약물',
        leftDays: '최소 남은 일수',
        todayChecklist: '오늘의 추천/체크',
        checklistLoading: '알림 내역을 분석 중입니다...',
        uploadTitle: '새로운 처방전/진단서 스캔 추가',
        uploadSubtitle: '어려운 의료 문서, 인공지능이 쉽게 분석하고 요약해 드립니다. (이미지 선택 또는 드래그 가능)',
        uploadCta: '이곳을 클릭하여 사진 업로드 공간으로 이동',
        uploadHint: 'jpg, png 포맷 지원 (10MB 이하)',
        goRecommendationButton: 'AI 추천 보기',
        goChatbotButton: 'AI 상담 시작',
        fallbackName: '알수없음',
        nameLoading: '로딩 중...',
        nameSuffix: '님',
        emptyValue: '미입력',
        recentPrescriptionTitle: '최근 처방',
        noDrugInfo: '약품 정보 없음',
        noDiseaseInfo: '질환 정보 없음',
        medDoneTitle: '오늘 복약 미션 완료!',
        medDoneBody: '모든 약을 잘 챙겨드셨습니다.',
        medPendingTitle: '아직 오늘 복약하지 않으셨습니다.',
        medPendingBody: '잊지 말고 약을 챙겨드세요.',
        medEmptyTitle: '오늘 등록된 복약 일정이 없습니다.',
        medEmptyBody: '처방전을 스캔하거나 직접 등록해보세요.',
        healthDoneTitle: '건강관리 목표 달성!',
        healthDoneBody: '오늘의 일상 목표를 달성했습니다.',
        healthPendingTitle: '오늘 건강관리 체크가 남아 있습니다.',
        healthPendingBody: '물 마시기, 걷기, 스트레칭 체크를 진행해보세요.',
        errorPrefix: '데이터를 불러오는 중 오류가 발생했습니다: ',
    },
    medications: {
        title: '전체 복약 기록 관리',
        subtitle: '오늘 드셔야 할 약과 지금까지의 이력을 확인하고 체크하세요.',
        loading: '복약 데이터를 불러오는 중입니다...',
        recentButton: '최근 2주 일정',
        newScanButton: '새 처방전 등록',
        emptyTitle: '등록된 복약 일정이 없습니다.',
        emptySubtitle: '처방전을 스캔하여 자동으로 복약 일정을 생성하세요.',
        noItems: '등록된 복약 체크 항목이 없습니다.',
        taken: '복용 완료',
        skipped: '미복용',
        noRecord: '기록 없음',
        loadError: '데이터를 불러오지 못했습니다: ',
        updateError: '업데이트 중 오류가 발생했습니다: ',
        daySuffix: ' 일정',
    },
    health: {
        title: '일상 건강 활동',
        subtitle: '수분 섭취, 운동, 수면 등 추천받은 일일 미션을 수행하세요.',
        sectionTitle: '오늘 및 최근 건강 기록',
        emptyTitle: '등록된 건강관리 활동이 없습니다.',
        emptySubtitle: '목표를 설정하거나 처방 기반 추천을 받아 시작해보세요.',
        done: '완료',
        pending: '미완료',
        loadError: '데이터를 불러오지 못했습니다: ',
        updateError: '업데이트 중 오류가 발생했습니다: ',
    },
    profile: {
        title: '내 건강 프로필 설정',
        subtitle: '정확한 정보를 입력할수록 더 정교한 분석 결과를 받으실 수 있습니다.',
        photoTitle: '프로필 사진',
        loadingEmail: '계정 로딩 중...',
        changePhoto: '사진 변경하기',
        formTitle: '기본 정보 수정',
        name: '이름',
        birthday: '생년월일 (YYYY-MM-DD)',
        gender: '성별',
        phone: '휴대폰 번호',
        genderNone: '선택 안함',
        genderMale: '남성',
        genderFemale: '여성',
        phonePlaceholder: '010-1234-5678',
        saveButton: '정보 저장하기',
        updateSuccess: '정보가 성공적으로 업데이트 되었습니다.',
        uploadLoading: '업로드 중입니다...',
        uploadSuccess: '사진이 업데이트 되었습니다.',
    },
    recommendations: {
        title: 'AI 맞춤 추천 콘텐츠',
        subtitle: '입력하신 신체 정보와 처방전/진단서 분석을 바탕으로 AI가 제안합니다.',
        emptyTitle: '아직 맞춤 추천 내역이 생성되지 않았습니다.',
        emptySubtitle: '프로필 정보를 채우거나 처방전을 등록하시면 AI가 똑똑하게 분석합니다.',
        scanButton: '처방전 스캔하러 가기',
        chatbotButton: 'AI 상담으로 이어가기',
        toastThanks: '소중한 의견 감사합니다. 추천 알고리즘에 반영되었습니다!',
        disabledMessage: 'AI가 이 콘텐츠를 더 이상 추천하지 않습니다.',
        badgeSelected: '활성 추천',
        cardTitle: 'AI 추천',
        scoreLabel: '점수',
        rankLabel: '순위',
        helpful: '도움이 되셨나요?',
        loadError: '데이터를 불러오지 못했습니다: ',
    },
    chatbot: {
        title: 'AI 건강 상담',
        subtitle: '복약 상담과 생활 건강 질문을 한 화면에서 바로 이어갈 수 있습니다.',
        setupTitle: '상담 설정',
        setupSubtitle: '상담 모드를 고르고 필요한 정보만 입력해 주세요.',
        modeLabel: '상담 모드',
        modeMedication: '복약 상담',
        modeHealth: '생활 건강 상담',
        diseaseCodeLabel: '질환 코드 또는 질환명',
        diseaseCodePlaceholder: '예: J00 또는 감기',
        medicationsLabel: '현재 복용 중인 약',
        medicationsPlaceholder: '약 이름을 쉼표(,)로 구분해서 입력하세요.\n예: 타이레놀, 무스렉스',
        historyTitle: '최근 복약 상담 참고 이력',
        historyLoading: '이력을 불러오는 중입니다...',
        historyEmpty: '아직 저장된 복약 상담 참고 이력이 없습니다.',
        historyNoDisease: '질환 정보 없음',
        historyNoMedication: '약 정보 없음',
        historyError: '복약 상담 이력을 불러오지 못했습니다: ',
        refreshHistory: '새로고침',
        chatTitle: '대화창',
        chatSubtitle: '질문을 보내면 AI가 현재 모드에 맞춰 답변합니다.',
        welcomeMessage: '안녕하세요. 복약 상담이나 생활 건강 고민을 편하게 남겨 주세요.',
        questionLabel: '질문 입력',
        questionPlaceholder: '예: 이 약은 식후에 먹어야 하나요?',
        sendButton: '질문 보내기',
        resetButton: '대화 비우기',
        assistantName: 'AI 상담사',
        userName: '나',
        patientIdLabel: '내 ID',
        ready: '상담 준비가 완료되었습니다.',
        patientCheckFailed: '현재 사용자 정보가 상담 대상과 연결되지 않았습니다.',
        userMissing: '사용자 정보를 확인할 수 없어 상담을 시작할 수 없습니다.',
        questionRequired: '질문을 먼저 입력해 주세요.',
        medicationsRequired: '복약 상담 모드에서는 현재 복용 중인 약을 한 개 이상 입력해 주세요.',
        sending: '질문을 전송하고 있습니다...',
        success: '답변이 도착했습니다.',
        emptyAnswer: '답변을 받아오지 못했습니다.',
        errorReply: '죄송합니다. 답변을 가져오는 중 문제가 생겼습니다.',
        initError: '상담 초기화 중 문제가 발생했습니다: ',
    },
    scans: {
        title: '처방전 자동 입력',
        subtitle: '사진을 올리시면 AI가 약물 정보를 분석해 복약 일정에 자동으로 넣어드립니다.',
        cardTitle: '새 처방전/기록 등록',
        docTypeLabel: '문서 종류 선택',
        prescriptionOption: '처방전 (약국 봉투)',
        recordOption: '진단서/소견서',
        uploadTitle: '이미지 선택하기',
        uploadSubtitle: '또는 여기에 파일을 끌어다 놓으세요.',
        analyzeButton: 'AI 분석 시작하기',
        emptyTitle: '아직 분석된 문서가 없습니다.',
        emptySubtitle: '좌측에서 이미지를 업로드하고 분석을 시작하세요.',
        resultTitle: '분석 결과',
        resultReady: '확인 가능',
        editTitle: '분석 결과 수정',
        editSubtitle: '날짜와 약품을 직접 다듬은 뒤 저장할 수 있습니다.',
        documentDate: '문서 날짜',
        diagnosis: '진단명',
        diagnosisPlaceholder: '예: 감기',
        clinicalNote: '진료 요약',
        clinicalNotePlaceholder: '진료기록지 내용을 정리해 입력하세요.',
        drugLabel: '약품 선택',
        drugPlaceholder: '약 이름을 검색하세요. 예: 무스리',
        drugHelp: '약품은 DB 검색 결과에서 선택해 추가합니다.',
        noSelectedDrugs: '선택된 약품이 없습니다.',
        noManufacturer: '제조사 정보 없음',
        refreshButton: '최신 결과 다시 불러오기',
        updateButton: '수정 내용 반영',
        saveButton: '내 복약 및 추천 목록에 적용하기',
        uploadLoading: '업로드 중...',
        uploadSuccess: '파일이 서버에 안전하게 업로드 되었습니다. 분석하거나 직접 수정할 수 있습니다.',
        preEditWarning: '업로드는 완료되었습니다. OCR 분석 전에도 필요한 값을 직접 입력할 수 있습니다.',
        resultUpdated: '수정한 내용이 반영되었습니다.',
        saveSummaryTitle: '저장 결과 안내',
        prescriptionSavedTitle: '처방전 저장이 완료되었습니다.',
        recordSavedTitle: '진료기록 저장이 완료되었습니다.',
        createdCountLabel: '새로 생성된 복약 일정',
        skippedCountLabel: '중복으로 건너뛴 약품',
        skippedListLabel: '중복 약품 목록',
        recommendationSavedLabel: '활성 추천 저장 건수',
        recommendationReady: '추천도 함께 준비되었습니다.',
        recommendationEmpty: '추천은 아직 활성 저장되지 않았습니다.',
        chatbotHint: '저장된 추천을 확인한 뒤 AI 상담에서 복약 질문까지 바로 이어갈 수 있습니다.',
        goMedicationButton: '복약 관리로 이동',
        goRecommendationButton: 'AI 추천 보러 가기',
        goChatbotButton: 'AI 상담으로 이어가기',
        goHealthButton: '건강 기록 보러 가기',
        saveDetailPrefix: '저장 상세: ',
        noDrugsDetected: '인식된 약물이 없습니다. 아래에서 직접 선택해 주세요.',
        extractedDrugTitle: '발견된 약품 정보',
        extractedDrugHint: 'OCR/AI 분석 결과에 포함된 약품명입니다.',
        rawTextTitle: '추출된 텍스트 요약:',
        analysisFailed: '분석 실패',
        documentDateLabel: '문서 날짜:',
        diagnosisLabel: '진단명:',
        clinicalNoteLabel: '진료 요약:',
        scanSaveSuccess: '성공적으로 저장되었습니다! 복약 기록과 AI 추천 메뉴에서 내역을 확인할 수 있습니다.',
        scanSaveError: '저장 실패: ',
        recommendationSaveError: '추천 활성 저장 실패: ',
        updateError: '수정 반영 실패: ',
        analyzeErrorPrefix: '분석 중 오류가 발생했습니다.',
        analyzeActionLoading: 'AI가 꼼꼼히 읽고 있습니다...',
        reanalyzeButton: '재분석 하기',
        uploadFirst: '먼저 파일을 정상적으로 업로드해주세요.',
        saveLoading: '저장 중...',
    },
};

window.getText = function (path, fallback = '') {
    const value = path.split('.').reduce((acc, key) => (acc && acc[key] !== undefined ? acc[key] : undefined), window.APP_TEXTS);
    return value === undefined ? fallback : value;
};

window.applyTextBindings = function (scope = document) {
    scope.querySelectorAll('[data-text]').forEach((el) => {
        const text = window.getText(el.dataset.text, el.innerText);
        el.innerText = text;
    });

    scope.querySelectorAll('[data-placeholder]').forEach((el) => {
        const text = window.getText(el.dataset.placeholder, el.getAttribute('placeholder') || '');
        el.setAttribute('placeholder', text);
    });

    scope.querySelectorAll('[data-title]').forEach((el) => {
        const text = window.getText(el.dataset.title, el.getAttribute('title') || '');
        el.setAttribute('title', text);
    });
};
